version: '3'

services:

  bot:
    build: bot
    env_file:
      - ./bot/.env
    environment:
      SELENIUM_GRID_URL: http://selenium:4444/wd/hub
      DATABASE_URL: postgres://postgres@db/
    ports:
      - 17296:80
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

  cron:
    build: cron
    restart: unless-stopped

  db:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres: